// <auto-generated />
using System;
using GymProJectv2.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymProJectv2.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20210316124411_03162021")]
    partial class _03162021
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.DichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenDV")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.GiaoAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaGiaoAn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomGiaoAn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenGiaoAn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("GiaoAns");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChiChiNhanh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IDNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MaChiNhanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKHLienQuan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNVBanHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNVLapPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayLapHD")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDoanhNghiep")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenNVBanHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNVLapPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HoaDonSanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("IDHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDHoaDon");

                    b.HasIndex("IDSanPham");

                    b.ToTable("HoaDonSanPhams");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HocVienDKLopHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChiNhanh")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("IDDichVu")
                        .HasColumnType("int");

                    b.Property<int>("IDKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IDLopHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianHoc")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDDichVu");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDLopHoc");

                    b.ToTable("HocVienDKLopHocs");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LoaiKH")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKH")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoTKNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LapGiaoAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDGiaoAn")
                        .HasColumnType("int");

                    b.Property<int>("IDLopHoc")
                        .HasColumnType("int");

                    b.Property<int>("IDNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongHocVien")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKhaiGiang")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDGiaoAn");

                    b.HasIndex("IDLopHoc");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("LapGiaoAns");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LapPhieuChi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<int>("IDPhieuChi")
                        .HasColumnType("int");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDPhieuChi");

                    b.HasIndex("IDSanPham");

                    b.ToTable("LapPhieuChis");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LapPhieuThu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("IDKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IDPhieuThu")
                        .HasColumnType("int");

                    b.Property<int>("IDSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDPhieuThu");

                    b.HasIndex("IDSanPham");

                    b.ToTable("LapPhieuThus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LopHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaLop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLop")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMND")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.NhomHangHoa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaNhomHangHoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhomHangHoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhomHangHoas");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuChi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("HinhThucChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IDNhanVienBanHang")
                        .HasColumnType("int");

                    b.Property<int?>("IDNhanVienLapPhieu")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhieuChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDoChi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaNguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhieuChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayLapPhieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoPhieuChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TTLienLac")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNVBanHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNVLapPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhanVienChiuTrachNhiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("IDNhanVienBanHang");

                    b.HasIndex("IDNhanVienLapPhieu");

                    b.HasIndex("KhachHangID");

                    b.ToTable("PhieuChis");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuDanhGiaHLV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("IDHuanLuyenVien")
                        .HasColumnType("int");

                    b.Property<int?>("IDNhanVienDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("IDTieuChiDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MaPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("IDHuanLuyenVien");

                    b.HasIndex("IDNhanVienDanhGia");

                    b.HasIndex("IDTieuChiDanhGia");

                    b.ToTable("PhieuDanhGiaHLVs");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuThu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<int?>("IDKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IDNhanVienBanHang")
                        .HasColumnType("int");

                    b.Property<int?>("IDNhanVienLapPhieu")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhieuThu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDoNop")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MaPhieuThu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayLapPhieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoPhieuThu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVienBanHang");

                    b.HasIndex("IDNhanVienLapPhieu");

                    b.ToTable("PhieuThus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.SanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDNhomHangHoa")
                        .HasColumnType("int");

                    b.Property<string>("MaSP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("IDNhomHangHoa");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.TieuChiDanhGia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiemToiDa")
                        .HasColumnType("int");

                    b.Property<string>("LoaiTieuChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenTieuChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("TieuChiDanhGias");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HoaDon", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HoaDonSanPham", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.HoaDon", "HoaDon")
                        .WithMany("HoaDonSanPhams")
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.SanPham", "SanPham")
                        .WithMany("HoaDonSanPhams")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HocVienDKLopHoc", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.DichVu", "DichVu")
                        .WithMany("HocVienDKLopHocs")
                        .HasForeignKey("IDDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.KhachHang", "KhachHang")
                        .WithMany("HocVienDKLopHocs")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.LopHoc", "LopHoc")
                        .WithMany("HocVienDKLopHocs")
                        .HasForeignKey("IDLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LapGiaoAn", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.GiaoAn", "GiaoAn")
                        .WithMany("LapGiaoAns")
                        .HasForeignKey("IDGiaoAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.LopHoc", "LopHoc")
                        .WithMany("LapGiaoAns")
                        .HasForeignKey("IDLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien")
                        .WithMany("LapGiaoAns")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoAn");

                    b.Navigation("LopHoc");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LapPhieuChi", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.PhieuChi", "PhieuChi")
                        .WithMany("LapPhieuChis")
                        .HasForeignKey("IDPhieuChi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.SanPham", "SanPham")
                        .WithMany("LapPhieuChis")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuChi");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LapPhieuThu", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.PhieuThu", "PhieuThu")
                        .WithMany("LapPhieuThus")
                        .HasForeignKey("IDPhieuThu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymProJectv2.DataModel.Entity.SanPham", "SanPham")
                        .WithMany("LapPhieuThus")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuThu");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuChi", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien_IDNhanVienBanHang")
                        .WithMany("PhieuChi_IDNhanVienBanHangs")
                        .HasForeignKey("IDNhanVienBanHang");

                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien_IDNhanVienLapPhieu")
                        .WithMany("PhieuChi_IDNhanVienLapPhieus")
                        .HasForeignKey("IDNhanVienLapPhieu");

                    b.HasOne("GymProJectv2.DataModel.Entity.KhachHang", null)
                        .WithMany("PhieuChis")
                        .HasForeignKey("KhachHangID");

                    b.Navigation("NhanVien_IDNhanVienBanHang");

                    b.Navigation("NhanVien_IDNhanVienLapPhieu");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuDanhGiaHLV", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien_IDHuanLuyenVien")
                        .WithMany("PhieuDanhGiaHLV_IDHuanLuyenViens")
                        .HasForeignKey("IDHuanLuyenVien");

                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien_IDNhanVienDanhGia")
                        .WithMany("PhieuDanhGiaHLV_IDNhanVienDanhGias")
                        .HasForeignKey("IDNhanVienDanhGia");

                    b.HasOne("GymProJectv2.DataModel.Entity.TieuChiDanhGia", "TieuChiDanhGia")
                        .WithMany("PhieuDanhGiaHLVs")
                        .HasForeignKey("IDTieuChiDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien_IDHuanLuyenVien");

                    b.Navigation("NhanVien_IDNhanVienDanhGia");

                    b.Navigation("TieuChiDanhGia");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuThu", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.KhachHang", "KhachHang")
                        .WithMany("PhieuThus")
                        .HasForeignKey("IDKhachHang");

                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien_IDNhanVienBanHang")
                        .WithMany("PhieuThu_IDNhanVienBanHangs")
                        .HasForeignKey("IDNhanVienBanHang");

                    b.HasOne("GymProJectv2.DataModel.Entity.NhanVien", "NhanVien_IDNhanVienLapPhieu")
                        .WithMany("PhieuThu_IDNhanVienLapPhieus")
                        .HasForeignKey("IDNhanVienLapPhieu");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien_IDNhanVienBanHang");

                    b.Navigation("NhanVien_IDNhanVienLapPhieu");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.SanPham", b =>
                {
                    b.HasOne("GymProJectv2.DataModel.Entity.NhomHangHoa", "NhomHangHoa")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDNhomHangHoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomHangHoa");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.DichVu", b =>
                {
                    b.Navigation("HocVienDKLopHocs");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.GiaoAn", b =>
                {
                    b.Navigation("LapGiaoAns");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.HoaDon", b =>
                {
                    b.Navigation("HoaDonSanPhams");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.KhachHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HocVienDKLopHocs");

                    b.Navigation("PhieuChis");

                    b.Navigation("PhieuThus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.LopHoc", b =>
                {
                    b.Navigation("HocVienDKLopHocs");

                    b.Navigation("LapGiaoAns");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LapGiaoAns");

                    b.Navigation("PhieuChi_IDNhanVienBanHangs");

                    b.Navigation("PhieuChi_IDNhanVienLapPhieus");

                    b.Navigation("PhieuDanhGiaHLV_IDHuanLuyenViens");

                    b.Navigation("PhieuDanhGiaHLV_IDNhanVienDanhGias");

                    b.Navigation("PhieuThu_IDNhanVienBanHangs");

                    b.Navigation("PhieuThu_IDNhanVienLapPhieus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.NhomHangHoa", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuChi", b =>
                {
                    b.Navigation("LapPhieuChis");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.PhieuThu", b =>
                {
                    b.Navigation("LapPhieuThus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.SanPham", b =>
                {
                    b.Navigation("HoaDonSanPhams");

                    b.Navigation("LapPhieuChis");

                    b.Navigation("LapPhieuThus");
                });

            modelBuilder.Entity("GymProJectv2.DataModel.Entity.TieuChiDanhGia", b =>
                {
                    b.Navigation("PhieuDanhGiaHLVs");
                });
#pragma warning restore 612, 618
        }
    }
}
